name: quick_environment # but not that quick! 

channels:
  - conda-forge
  - defaults
dependencies:
  - seaborn=0.13.0 
  - pandas=2.1.1
  - matplotlib=3.8
  - numpy=1.26.0
  - statsmodels=0.14.0
  - scikit-learn=1.3.2
  - scipy=1.11.3
